### ISSUE TITLE
Better types

### ISSUE THREAD

**Issue by pc-erin** [EthanRBrown/arrayset.js#27]
Have you considered adding better types to this library?
As is, it's kind of unusable for most typescript codebases.

Just adding a single type parameter for the input and output would be a massive improvement.

**Comment by EthanRBrown** [comment]
That would be nice, but currently low on my list of priorities.  I would welcome a PR.

**Comment by EthanRBrown** [comment]
Closed with #28 ; thanks, @pc-erin !
